// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolyMarket.Storage.Data;

#nullable disable

namespace PolyMarket.Storage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207184557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolyMarket.Storage.Entities.AnomalyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<decimal>("Severity")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_anomalies_market_ts");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.MarketEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.PriceHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Liquidity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("liquidity");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<decimal>("NoPrice")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("no_price");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Volume24h")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("volume_24h");

                    b.Property<decimal>("YesPrice")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("yes_price");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_price_history_market_ts");

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.WhaleTradeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("price");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<decimal>("Size")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TraderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trader_address");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_whale_trades_market_ts");

                    b.ToTable("whale_trades", (string)null);
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.AnomalyEntity", b =>
                {
                    b.HasOne("PolyMarket.Storage.Entities.MarketEntity", "Market")
                        .WithMany("Anomalies")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.PriceHistoryEntity", b =>
                {
                    b.HasOne("PolyMarket.Storage.Entities.MarketEntity", "Market")
                        .WithMany("PriceHistory")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.WhaleTradeEntity", b =>
                {
                    b.HasOne("PolyMarket.Storage.Entities.MarketEntity", "Market")
                        .WithMany("WhaleTrades")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PolyMarket.Storage.Entities.MarketEntity", b =>
                {
                    b.Navigation("Anomalies");

                    b.Navigation("PriceHistory");

                    b.Navigation("WhaleTrades");
                });
#pragma warning restore 612, 618
        }
    }
}
